language: go

go:
  - "1.12.x"

# Enabling modules support
env:
  - GO111MODULE=on

# persistent file installation
install: true

before_install:
  - echo -e "machine github.com\n  login $CI_USER\n  password $CI_USER_PASSWORD" > ~/.netrc

script:
  - go test -v ./...

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

services:
  - docker
